repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: minio
    url: https://charts.min.io/

releases:
  - name: traefik
    namespace: ingress
    chart: traefik/traefik
    version: 34.1.0
    values:
      - values/traefik.yaml

  - name: cloudnative-pg
    namespace: data-platform
    chart: cnpg/cloudnative-pg
    version: 0.23.2

  - name: postgresql
    namespace: data-platform
    chart: cnpg/cluster
    version: 0.0.12
    values:
      - values/postgresql.yaml

  - name: minio
    namespace: data-platform
    chart: minio/minio
    version: 5.4.0
    values:
      - values/minio.yaml

  - name: airflow
    namespace: data-platform
    chart: apache-airflow/airflow
    version: 1.15.0
    values:
      - values/airflow.yaml

  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 68.2.0
    values:
      - values/prometheus.yaml

  - name: loki
    namespace: monitoring
    chart: grafana/loki
    version: 6.24.0
    values:
      - values/loki.yaml

  - name: dex
    namespace: identity
    chart: dex/dex
    version: 0.19.1
    values:
      - values/dex.yaml

  - name: oauth2-proxy
    namespace: identity
    chart: oauth2-proxy/oauth2-proxy
    version: 7.12.0
    values:
      - values/oauth2-proxy.yaml

  - name: mailpit
    namespace: taxi-app
    chart: mailpit/mailpit
    version: 0.1.0
    values:
      - values/mailpit.yaml
