apiVersion: v1
kind: Service
metadata:
  name: taxi-dashboard
  labels:
    app.kubernetes.io/name: taxi-dashboard
spec:
  selector:
    app.kubernetes.io/name: taxi-dashboard
  ports:
    - name: http
      port: 8501
      targetPort: http
